### ISSUE TITLE
Pop up in food menu

### ISSUE THREAD

**Issue by BhavanaSJain** [softkoash-ashishjain/brunchery_v1#78] opened 2018-08-28 10:53 UTC
![image](https://user-images.githubusercontent.com/8385702/44718707-8bd12000-aade-11e8-9fc1-3ff48988e85a.png)

**Comment by softventure** [comment] 2018-09-01 19:44
@sawantsh Please take a look.

**Comment by softventure** [comment] 2018-09-03 17:27
@BhavanaSJain Now this looks to be a duplicate of issue #121. Please clean up duplicate items, so we do not spend double efforts.

**Closed** 2018-09-08 09:31 UTC
Labels: duplicate, ui
